### ISSUE TITLE
Duplicate Tasknames

### ISSUE THREAD

**Issue by ynn1k** [ynn1k/simple-js-tasklist#2]
Having Tasks with same name causes an unwanted behaviour.
completing or deleting one of those tasks deletes or completes them all - since no id is set.

**Comment by Troy96** [comment]
Hi @ynn1k ,

Can I take this up for Hacktoberfest?

**Comment by ynn1k** [comment]
Yes would appreciate it. Assigned you the issue :)

**Comment by ynn1k** [comment]
solved in 37e47d32319668c1900f365f472b8ab8c89bb7f3
