### ISSUE TITLE
Add a "clear completed tasks only" button

### ISSUE THREAD

**Issue by ynn1k** [ynn1k/simple-js-tasklist#4]
Add a button thats only removes the completed tasks instead of all tasks.

**Comment by Swayamsvk** [comment]
Can I work on this?

**Comment by ynn1k** [comment]
Go for it. I assigned this issue to you.

**Comment by Antonio-Bennett** [comment]
Hi @ynn1k Could you go ahead and assign me this issue while looking at my PR :) related to my school assignment. Let me know if I should change anything in my PR as well :)
